version: "3.7"

services:
  app:
    build:
        context: .
        dockerfile: Dockerfile
    command: npm run start:prod
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ride_hailing
      - DATABASE_URL="postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DB}?schema=public"
      - WOMPI_PUBLIC_KEY=pub_test_EjcgGnHhlLadwW52vNRlX2iGM31wRYLM
      - WOMPI_URL=https://sandbox.wompi.co/v1/
      - TOKEN_OPENROUTE_SERVICE=5b3ce3597851110001cf6248371183c5d69c41d184c801efce72e411
      - NODE_ENV=production


    networks:
      - backend

  db:
    image: postgres
    hostname: postgres
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ride_hailing
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    depends_on:
      - db
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    restart: unless-stopped
    networks:
      - backend

volumes:
  postgres-data:
  pgadmin-data:

networks:
  backend:
    name: backend